# Define the directory where HTML files will be created
$directory = "K:\MCORTESGRANADOS_AWS_BUCKET\IT\DOT_NET\C_SHARP\03_ADVANCED"

# Define the list of file names
$fileNames = @(
    "c_sharp_advanced_01_task_based_asynchronous_pattern.html",
    "c_sharp_advanced_02_parallel_programming.html",
    "c_sharp_advanced_03_advanced_linq.html",
    "c_sharp_advanced_04_advanced_generics.html",
    "c_sharp_advanced_05_metaprogramming.html",
    "c_sharp_advanced_06_dynamic_language_runtime.html",
    "c_sharp_advanced_07_memory_management.html",
    "c_sharp_advanced_08_interoperability.html",
    "c_sharp_advanced_09_unsafe_code.html",
    "c_sharp_advanced_10_compiler_directives.html",
    "c_sharp_advanced_11_custom_attributes.html",
    "c_sharp_advanced_12_advanced_delegates.html",
    "c_sharp_advanced_13_dynamic_types.html",
    "c_sharp_advanced_14_custom_collections.html",
    "c_sharp_advanced_15_advanced_multithreading.html",
    "c_sharp_advanced_16_aspect_oriented_programming.html",
    "c_sharp_advanced_17_advanced_exception_handling.html",
    "c_sharp_advanced_18_source_generators.html",
    "c_sharp_advanced_19_span_and_memory.html",
    "c_sharp_advanced_20_records_and_positional_parameters.html",
    "c_sharp_advanced_21_expression_bodies.html",
    "c_sharp_advanced_22_local_functions.html",
    "c_sharp_advanced_23_indexers.html",
    "c_sharp_advanced_24_lazy_initialization.html",
    "c_sharp_advanced_25_thread_synchronization.html",
    "c_sharp_advanced_26_inversion_of_control.html",
    "c_sharp_advanced_27_dependency_injection.html",
    "c_sharp_advanced_28_aspect_oriented_programming.html",
    "c_sharp_advanced_29_advanced_reflection.html",
    "c_sharp_advanced_30_memory_layout.html",
    "c_sharp_advanced_31_thread_local_storage.html",
    "c_sharp_advanced_32_safe_handle.html",
    "c_sharp_advanced_33_thread_pool.html",
    "c_sharp_advanced_34_advanced_async.html",
    "c_sharp_advanced_35_custom_serialization.html",
    "c_sharp_advanced_36_advanced_interoperability.html",
    "c_sharp_advanced_37_code_analysis.html",
    "c_sharp_advanced_38_advanced_design_patterns.html",
    "c_sharp_advanced_39_dll_import.html",
    "c_sharp_advanced_40_advanced_linq_operators.html",
    "c_sharp_advanced_41_advanced_object_pooling.html",
    "c_sharp_advanced_42_cross_platform_development.html",
    "c_sharp_advanced_43_high_performance_computing.html",
    "c_sharp_advanced_44_advanced_file_io.html",
    "c_sharp_advanced_45_network_programming.html",
    "c_sharp_advanced_46_web_sockets.html",
    "c_sharp_advanced_47_security_and_encryption.html",
    "c_sharp_advanced_48_custom_collection_implementations.html",
    "c_sharp_advanced_49_advanced_apis.html",
    "c_sharp_advanced_50_advanced_event_handling.html",
    "c_sharp_advanced_51_data_binding.html",
    "c_sharp_advanced_52_advanced_garbage_collection.html",
    "c_sharp_advanced_53_performance_tuning.html",
    "c_sharp_advanced_54_delegates_and_events.html",
    "c_sharp_advanced_55_custom_code_generators.html",
    "c_sharp_advanced_56_advanced_inheritance.html",
    "c_sharp_advanced_57_custom_providers.html",
    "c_sharp_advanced_58_memory_management_optimizations.html",
    "c_sharp_advanced_59_advanced_threading_patterns.html",
    "c_sharp_advanced_60_diagnostics_and_tracing.html",
    "c_sharp_advanced_61_custom_code_analysis_tools.html",
    "c_sharp_advanced_62_asynchronous_streams.html",
    "c_sharp_advanced_63_enumerable_vs_enumerator.html",
    "c_sharp_advanced_64_advanced_data_structures.html",
    "c_sharp_advanced_65_custom_converters.html",
    "c_sharp_advanced_66_advanced_string_operations.html",
    "c_sharp_advanced_67_code_refactoring.html",
    "c_sharp_advanced_68_interprocess_communication.html",
    "c_sharp_advanced_69_parallel_for_each.html",
    "c_sharp_advanced_70_task_completion_source.html",
    "c_sharp_advanced_71_custom_exceptions.html",
    "c_sharp_advanced_72_advanced_lambda_expressions.html",
    "c_sharp_advanced_73_advanced_attributes.html",
    "c_sharp_advanced_74_custom_disposables.html",
    "c_sharp_advanced_75_async_await_patterns.html",
    "c_sharp_advanced_76_advanced_data_access.html",
    "c_sharp_advanced_77_custom_resource_management.html",
    "c_sharp_advanced_78_async_streams.html",
    "c_sharp_advanced_79_advanced_garbage_collection_tuning.html",
    "c_sharp_advanced_80_thread_safe_collections.html",
    "c_sharp_advanced_81_custom_synchronization.html",
    "c_sharp_advanced_82_code_analysis_techniques.html",
    "c_sharp_advanced_83_custom_resolvers.html",
    "c_sharp_advanced_84_memory_profiler_tools.html",
    "c_sharp_advanced_85_custom_task_schedulers.html",
    "c_sharp_advanced_86_custom_io_operations.html",
    "c_sharp_advanced_87_advanced_event_implementation.html",
    "c_sharp_advanced_88_intermediate_code_generation.html",
    "c_sharp_advanced_89_advanced_implementation_patterns.html",
    "c_sharp_advanced_90_custom_data_structures.html",
    "c_sharp_advanced_91_low_level_programming.html",
    "c_sharp_advanced_92_custom_data_transformations.html",
    "c_sharp_advanced_93_high_performance_design.html",
    "c_sharp_advanced_94_custom_network_protocols.html",
    "c_sharp_advanced_95_advanced_xml_handling.html",
    "c_sharp_advanced_96_advanced_json_handling.html",
    "c_sharp_advanced_97_custom_logging_frameworks.html",
    "c_sharp_advanced_98_advanced_exception_handling_patterns.html",
    "c_sharp_advanced_99_interoperability_with_legacy_systems.html",
    "c_sharp_advanced_100_cross_thread_operations.html",
    "c_sharp_advanced_101_custom_memory_allocators.html",
    "c_sharp_advanced_102_advanced_compression.html",
    "c_sharp_advanced_103_advanced_object_caching.html",
    "c_sharp_advanced_104_advanced_messaging_patterns.html",
    "c_sharp_advanced_105_custom_serialization_formats.html",
    "c_sharp_advanced_106_advanced_io_streams.html",
    "c_sharp_advanced_107_advanced_data_access_patterns.html",
    "c_sharp_advanced_108_advanced_api_design.html",
    "c_sharp_advanced_109_custom_ui_controls.html",
    "c_sharp_advanced_110_code_injection.html",
    "c_sharp_advanced_111_custom_runtime_behavior.html",
    "c_sharp_advanced_112_advanced_language_features.html",
    "c_sharp_advanced_113_custom_data_stores.html",
    "c_sharp_advanced_114_advanced_database_interactions.html",
    "c_sharp_advanced_115_advanced_security_practices.html",
    "c_sharp_advanced_116_advanced_threading_issues.html",
    "c_sharp_advanced_117_advanced_exception_patterns.html",
    "c_sharp_advanced_118_advanced_file_system_operations.html",
    "c_sharp_advanced_119_advanced_object_reuse.html"
)

# Ensure the directory exists
if (-not (Test-Path $directory)) {
    New-Item -Path $directory -ItemType Directory
}

# Loop through each file name and create an empty HTML file
foreach ($fileName in $fileNames) {
    $filePath = Join-Path -Path $directory -ChildPath $fileName

    # Create the file
    New-Item -Path $filePath -ItemType File -Force
    Write-Host "Created file: $filePath"
}

